import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TALKS = [
  {
    conference: 'React Conf',
    description: 'Learn how to build React applications that scale with your team and user base.',
    duration: 45,
    slides: 'https://slides.com/sarah/react-scalable',
    speaker: 'Sarah Johnson',
    tag: 'React',
    title: 'Building Scalable React Applications',
    videoUrl: 'https://youtube.com/watch?v=example1',
    year: 2024,
  },
  {
    conference: 'JSConf',
    description: 'Exploring upcoming JavaScript features and their impact on modern development.',
    duration: 60,
    speaker: 'Dan Abramov',
    tag: 'JavaScript',
    title: 'The Future of JavaScript',
    videoUrl: 'https://youtube.com/watch?v=example2',
    year: 2024,
  },
  {
    conference: 'TypeScript Summit',
    description: 'Advanced TypeScript patterns for enterprise applications.',
    duration: 50,
    slides: 'https://slides.com/emily/typescript-best',
    speaker: 'Emily Chen',
    tag: 'TypeScript',
    title: 'TypeScript Best Practices',
    year: 2023,
  },
  {
    conference: 'Next.js Conf',
    description: 'Overview of new features and improvements in Next.js 15.',
    duration: 40,
    slides: 'https://slides.com/vercel/nextjs15',
    speaker: 'Vercel Team',
    tag: 'Next.js',
    title: "Next.js 15: What's New",
    videoUrl: 'https://youtube.com/watch?v=example3',
    year: 2024,
  },
  {
    conference: 'Web Perf Summit',
    description: 'Techniques for optimizing web application performance.',
    duration: 55,
    speaker: 'Alex Rodriguez',
    tag: 'Performance',
    title: 'Web Performance Optimization',
    videoUrl: 'https://youtube.com/watch?v=example4',
    year: 2023,
  },
  {
    conference: 'GraphQL Summit',
    description: 'Real-world experiences implementing GraphQL at scale.',
    duration: 45,
    slides: 'https://slides.com/maria/graphql-production',
    speaker: 'Maria Santos',
    tag: 'GraphQL',
    title: 'GraphQL in Production',
    year: 2024,
  },
  {
    conference: 'CSS Day',
    description: 'Master modern CSS layout techniques.',
    duration: 35,
    slides: 'https://slides.com/david/css-mastery',
    speaker: 'David Kim',
    tag: 'CSS',
    title: 'CSS Grid and Flexbox Mastery',
    videoUrl: 'https://youtube.com/watch?v=example5',
    year: 2023,
  },
  {
    conference: 'DevX Conf',
    description: 'How to create effective developer tools and experiences.',
    duration: 50,
    speaker: 'Jennifer Liu',
    tag: 'DevTools',
    title: 'Building Developer Tools',
    year: 2024,
  },
  {
    conference: 'Frontend Arch Summit',
    description: 'Implementing micro-frontends in large-scale applications.',
    duration: 60,
    speaker: 'Robert Brown',
    tag: 'Architecture',
    title: 'Micro-frontends Architecture',
    videoUrl: 'https://youtube.com/watch?v=example6',
    year: 2023,
  },
  {
    conference: 'AI Dev Conference',
    description: 'Leveraging AI tools to enhance developer productivity.',
    duration: 45,
    slides: 'https://slides.com/lisa/ai-development',
    speaker: 'Lisa Wang',
    tag: 'AI',
    title: 'AI-Powered Development',
    year: 2024,
  },
  {
    conference: 'A11y Summit',
    description: 'Building inclusive web applications for all users.',
    duration: 40,
    speaker: 'Michael Thompson',
    tag: 'Accessibility',
    title: 'Accessibility in Modern Web Apps',
    videoUrl: 'https://youtube.com/watch?v=example7',
    year: 2023,
  },
  {
    conference: 'React Conf',
    description: 'From Redux to Zustand: choosing the right state management.',
    duration: 35,
    slides: 'https://slides.com/anna/state-management',
    speaker: 'Anna Petrov',
    tag: 'State Management',
    title: 'State Management Evolution',
    year: 2024,
  },
  // New talks added for more variety
  {
    conference: 'Vue.js Amsterdam',
    description: 'Deep dive into the Composition API and its benefits for large applications.',
    duration: 50,
    slides: 'https://slides.com/evan/vue-composition',
    speaker: 'Evan You',
    tag: 'Vue.js',
    title: 'Vue 3 Composition API Deep Dive',
    videoUrl: 'https://youtube.com/watch?v=vue-comp',
    year: 2023,
  },
  {
    conference: 'Svelte Summit',
    description: 'Building performant web applications with SvelteKit.',
    duration: 45,
    speaker: 'Rich Harris',
    tag: 'Svelte',
    title: 'SvelteKit: The Future of Web Development',
    videoUrl: 'https://youtube.com/watch?v=svelte-kit',
    year: 2024,
  },
  {
    conference: 'Angular Connect',
    description: 'Exploring the new control flow syntax and its performance benefits.',
    duration: 40,
    slides: 'https://slides.com/angular/control-flow',
    speaker: 'Alex Rickabaugh',
    tag: 'Angular',
    title: 'Angular Control Flow Revolution',
    year: 2024,
  },
  {
    conference: 'NodeConf',
    description: 'Best practices for building secure and scalable Node.js applications.',
    duration: 55,
    speaker: 'Matteo Collina',
    tag: 'Node.js',
    title: 'Node.js Security & Performance',
    videoUrl: 'https://youtube.com/watch?v=node-security',
    year: 2023,
  },
  {
    conference: 'Deno Conf',
    description: 'Why Deno 2.0 is ready for production and how to migrate.',
    duration: 35,
    slides: 'https://slides.com/deno/v2-production',
    speaker: 'Ryan Dahl',
    tag: 'Deno',
    title: 'Deno 2.0: Production Ready',
    year: 2024,
  },
  {
    conference: 'Jamstack Conf',
    description: 'Headless CMS strategies for modern web applications.',
    duration: 40,
    speaker: 'Netlify Team',
    tag: 'Jamstack',
    title: 'Headless CMS Best Practices',
    videoUrl: 'https://youtube.com/watch?v=headless-cms',
    year: 2023,
  },
  {
    conference: 'Web Components Summit',
    description: 'Building reusable components that work everywhere.',
    duration: 45,
    slides: 'https://slides.com/lit/web-components',
    speaker: 'Justin Fagnani',
    tag: 'Web Components',
    title: 'Universal Web Components with Lit',
    year: 2024,
  },
  {
    conference: 'CSS Day',
    description: 'Modern CSS techniques for creating stunning visual effects.',
    duration: 30,
    speaker: 'Ana Tudor',
    tag: 'CSS',
    title: 'CSS Magic: Advanced Visual Effects',
    videoUrl: 'https://youtube.com/watch?v=css-magic',
    year: 2024,
  },
  {
    conference: 'Frontend Masters Live',
    description: 'Testing strategies for modern React applications.',
    duration: 60,
    slides: 'https://slides.com/kent/react-testing',
    speaker: 'Kent C. Dodds',
    tag: 'Testing',
    title: 'React Testing Library Deep Dive',
    year: 2023,
  },
  {
    conference: 'ViteConf',
    description: 'How Vite is revolutionizing the frontend build ecosystem.',
    duration: 40,
    speaker: 'Evan You',
    tag: 'Build Tools',
    title: 'Vite: The Build Tool Revolution',
    videoUrl: 'https://youtube.com/watch?v=vite-revolution',
    year: 2024,
  },
  {
    conference: 'MongoDB World',
    description: 'Modern database patterns for web applications.',
    duration: 50,
    slides: 'https://slides.com/mongodb/modern-patterns',
    speaker: 'MongoDB Team',
    tag: 'Database',
    title: 'MongoDB for Modern Web Apps',
    year: 2023,
  },
  {
    conference: 'Redis Day',
    description: 'Using Redis for real-time applications and caching strategies.',
    duration: 45,
    speaker: 'Redis Labs',
    tag: 'Caching',
    title: 'Redis in Production: Best Practices',
    videoUrl: 'https://youtube.com/watch?v=redis-production',
    year: 2024,
  },
  {
    conference: 'Docker Day',
    description: 'Containerizing frontend applications for consistent deployments.',
    duration: 55,
    slides: 'https://slides.com/docker/frontend-containers',
    speaker: 'Docker Team',
    tag: 'DevOps',
    title: 'Frontend Containerization Strategies',
    year: 2023,
  },
  {
    conference: 'Kubernetes Summit',
    description: 'Orchestrating frontend deployments with Kubernetes.',
    duration: 60,
    speaker: 'Kelsey Hightower',
    tag: 'DevOps',
    title: 'Frontend on Kubernetes',
    videoUrl: 'https://youtube.com/watch?v=k8s-frontend',
    year: 2024,
  },
  {
    conference: 'Security BSides',
    description: 'Common security vulnerabilities in modern web applications.',
    duration: 40,
    slides: 'https://slides.com/security/web-vulns',
    speaker: 'Troy Hunt',
    tag: 'Security',
    title: 'Web Application Security Essentials',
    year: 2023,
  },
  {
    conference: 'PWA Summit',
    description: 'Building progressive web apps that feel native.',
    duration: 45,
    speaker: 'Google Chrome Team',
    tag: 'PWA',
    title: 'Progressive Web Apps in 2024',
    videoUrl: 'https://youtube.com/watch?v=pwa-2024',
    year: 2024,
  },
  {
    conference: 'React Native EU',
    description: 'Cross-platform development with React Native and Expo.',
    duration: 50,
    slides: 'https://slides.com/expo/cross-platform',
    speaker: 'Expo Team',
    tag: 'React Native',
    title: 'React Native & Expo: Mobile Development',
    year: 2023,
  },
  {
    conference: 'Flutter Engage',
    description: 'Building beautiful UIs with Flutter for web and mobile.',
    duration: 40,
    speaker: 'Google Flutter Team',
    tag: 'Flutter',
    title: 'Flutter for Web: Production Ready',
    videoUrl: 'https://youtube.com/watch?v=flutter-web',
    year: 2024,
  },
  {
    conference: 'WebAssembly Summit',
    description: 'Running high-performance code in the browser with WebAssembly.',
    duration: 55,
    slides: 'https://slides.com/wasm/browser-performance',
    speaker: 'Lin Clark',
    tag: 'WebAssembly',
    title: 'WebAssembly for Web Developers',
    year: 2023,
  },
  {
    conference: 'Design Systems Week',
    description: 'Building and maintaining design systems at scale.',
    duration: 45,
    speaker: 'Design System Team',
    tag: 'Design Systems',
    title: 'Scaling Design Systems',
    videoUrl: 'https://youtube.com/watch?v=design-systems',
    year: 2024,
  },
  {
    conference: 'Figma Config',
    description: 'Designer-developer collaboration in modern workflows.',
    duration: 35,
    slides: 'https://slides.com/figma/design-dev-collab',
    speaker: 'Figma Team',
    tag: 'Design',
    title: 'Design-Development Collaboration',
    year: 2023,
  },
  {
    conference: 'State of JS',
    description: 'Analysis of JavaScript ecosystem trends and developer preferences.',
    duration: 30,
    speaker: 'Sacha Greif',
    tag: 'Trends',
    title: 'JavaScript Ecosystem 2024',
    videoUrl: 'https://youtube.com/watch?v=js-ecosystem',
    year: 2024,
  },
  {
    conference: 'Chrome Dev Summit',
    description: 'New web platform features and browser capabilities.',
    duration: 40,
    slides: 'https://slides.com/chrome/web-platform',
    speaker: 'Chrome Team',
    tag: 'Web Platform',
    title: 'Web Platform Updates 2024',
    year: 2024,
  },
  {
    conference: 'Edge Conf',
    description: 'Building applications for edge computing environments.',
    duration: 50,
    speaker: 'Vercel Edge Team',
    tag: 'Edge Computing',
    title: 'Edge Computing for Frontend',
    videoUrl: 'https://youtube.com/watch?v=edge-frontend',
    year: 2023,
  },
  {
    conference: 'GraphQL Galaxy',
    description: 'Advanced GraphQL federation and schema design patterns.',
    duration: 55,
    slides: 'https://slides.com/apollo/graphql-federation',
    speaker: 'Apollo Team',
    tag: 'GraphQL',
    title: 'GraphQL Federation at Scale',
    year: 2024,
  },
  {
    conference: 'TypeScript Congress',
    description: 'Template literal types and advanced type manipulation.',
    duration: 45,
    speaker: 'Anders Hejlsberg',
    tag: 'TypeScript',
    title: 'Advanced TypeScript Patterns',
    videoUrl: 'https://youtube.com/watch?v=advanced-ts',
    year: 2023,
  },
  {
    conference: 'Remix Conf',
    description: 'Full-stack web development with Remix and modern standards.',
    duration: 50,
    slides: 'https://slides.com/remix/full-stack',
    speaker: 'Ryan Florence',
    tag: 'Remix',
    title: 'Full-Stack Web with Remix',
    year: 2024,
  },
  {
    conference: 'Astro Launch Week',
    description: 'Building fast, content-focused websites with Astro.',
    duration: 40,
    speaker: 'Fred Schott',
    tag: 'Astro',
    title: 'Astro: The Web Framework for Content',
    videoUrl: 'https://youtube.com/watch?v=astro-content',
    year: 2024,
  },
  {
    conference: 'TailwindCSS Connect',
    description: 'Advanced Tailwind CSS techniques and custom design systems.',
    duration: 35,
    slides: 'https://slides.com/tailwind/advanced-techniques',
    speaker: 'Adam Wathan',
    tag: 'TailwindCSS',
    title: 'Advanced Tailwind Techniques',
    year: 2023,
  },
  {
    conference: 'Storybook Day',
    description: 'Component-driven development and testing strategies.',
    duration: 45,
    speaker: 'Storybook Team',
    tag: 'Storybook',
    title: 'Component-Driven Development',
    videoUrl: 'https://youtube.com/watch?v=component-driven',
    year: 2024,
  },
  {
    conference: 'Electron Conf',
    description: 'Building cross-platform desktop apps with web technologies.',
    duration: 50,
    slides: 'https://slides.com/electron/desktop-apps',
    speaker: 'Electron Team',
    tag: 'Electron',
    title: 'Modern Desktop Apps with Electron',
    year: 2023,
  },
  {
    conference: 'Tauri Conf',
    description: 'Lightweight desktop applications with Rust and web frontends.',
    duration: 40,
    speaker: 'Tauri Team',
    tag: 'Tauri',
    title: 'Tauri: Rust-Powered Desktop Apps',
    videoUrl: 'https://youtube.com/watch?v=tauri-desktop',
    year: 2024,
  },
  {
    conference: 'Web3 Frontend',
    description: 'Building user interfaces for decentralized applications.',
    duration: 55,
    slides: 'https://slides.com/web3/frontend-dapps',
    speaker: 'Ethereum Foundation',
    tag: 'Web3',
    title: 'Frontend for Decentralized Apps',
    year: 2023,
  },
  {
    conference: 'React India',
    description: 'Server components and the future of React architecture.',
    duration: 60,
    speaker: 'Sebastian Markbåge',
    tag: 'React',
    title: 'React Server Components Deep Dive',
    videoUrl: 'https://youtube.com/watch?v=rsc-deep-dive',
    year: 2024,
  },
  {
    conference: 'JSConf EU',
    description: 'Machine learning in the browser with TensorFlow.js.',
    duration: 45,
    slides: 'https://slides.com/tensorflow/browser-ml',
    speaker: 'TensorFlow Team',
    tag: 'Machine Learning',
    title: 'ML in the Browser with TensorFlow.js',
    year: 2023,
  },
  {
    conference: 'Web Performance Conf',
    description: 'Core Web Vitals optimization strategies for 2024.',
    duration: 40,
    speaker: 'Google Web Team',
    tag: 'Performance',
    title: 'Core Web Vitals Optimization',
    videoUrl: 'https://youtube.com/watch?v=cwv-optimization',
    year: 2024,
  },
  {
    conference: 'Node.js Interactive',
    description: 'Building real-time applications with Node.js and WebSockets.',
    duration: 50,
    slides: 'https://slides.com/nodejs/realtime-apps',
    speaker: 'Node.js Foundation',
    tag: 'Node.js',
    title: 'Real-time Apps with Node.js',
    year: 2023,
  },
  {
    conference: 'Bun Conf',
    description: 'Fast JavaScript runtime and package manager for modern development.',
    duration: 35,
    speaker: 'Jarred Sumner',
    tag: 'Bun',
    title: 'Bun: The Fast JavaScript Runtime',
    videoUrl: 'https://youtube.com/watch?v=bun-runtime',
    year: 2024,
  },
  {
    conference: 'Fresh Conf',
    description: 'Island architecture and edge-side rendering with Fresh.',
    duration: 40,
    slides: 'https://slides.com/deno/fresh-islands',
    speaker: 'Deno Team',
    tag: 'Fresh',
    title: 'Fresh: Island Architecture',
    year: 2024,
  },
  {
    conference: 'Qwik City',
    description: 'Resumability and instant-on web applications.',
    duration: 45,
    speaker: 'Miško Hevery',
    tag: 'Qwik',
    title: 'Qwik: Resumable Web Applications',
    videoUrl: 'https://youtube.com/watch?v=qwik-resumable',
    year: 2023,
  },
  {
    conference: 'SolidJS Conf',
    description: 'Fine-grained reactivity without virtual DOM overhead.',
    duration: 50,
    slides: 'https://slides.com/solid/fine-grained-reactivity',
    speaker: 'Ryan Carniato',
    tag: 'SolidJS',
    title: 'SolidJS: Fine-Grained Reactivity',
    year: 2024,
  },
];

async function seed() {
  await Promise.all(
    TALKS.map(talk => {
      return prisma.talk.create({
        data: {
          conference: talk.conference,
          description: talk.description,
          duration: talk.duration,
          slides: talk.slides,
          speaker: talk.speaker,
          tag: talk.tag,
          title: talk.title,
          videoUrl: talk.videoUrl,
          year: talk.year,
        },
      });
    }),
  )
    .then(() => {
      return console.info('[SEED] Successfully created talk records');
    })
    .catch(e => {
      return console.error('[SEED] Failed to create talk records', e);
    });
}

seed();
