import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const TALKS = [
  {
    conference: 'JSConf',
    description: 'Exploring upcoming JavaScript features and their impact on modern development.',
    duration: 60,
    speaker: 'Dan Abramov',
    tag: 'JavaScript',
    title: 'The Future of JavaScript',
    videoUrl: 'https://youtube.com/watch?v=example2',
    year: 2024,
  },
  {
    conference: 'Vue.js Amsterdam',
    description: 'Deep dive into the Composition API and its benefits for large applications.',
    duration: 50,
    slides: 'https://slides.com/evan/vue-composition',
    speaker: 'Evan You',
    tag: 'Vue.js',
    title: 'Vue 3 Composition API Deep Dive',
    videoUrl: 'https://youtube.com/watch?v=vue-comp',
    year: 2023,
  },
  {
    conference: 'Svelte Summit',
    description: 'Building performant web applications with SvelteKit.',
    duration: 45,
    speaker: 'Rich Harris',
    tag: 'Svelte',
    title: 'SvelteKit: The Future of Web Development',
    videoUrl: 'https://youtube.com/watch?v=svelte-kit',
    year: 2024,
  },
  {
    conference: 'Angular Connect',
    description: 'Exploring the new control flow syntax and its performance benefits.',
    duration: 40,
    slides: 'https://slides.com/angular/control-flow',
    speaker: 'Alex Rickabaugh',
    tag: 'Angular',
    title: 'Angular Control Flow Revolution',
    year: 2024,
  },
  {
    conference: 'NodeConf',
    description: 'Best practices for building secure and scalable Node.js applications.',
    duration: 55,
    speaker: 'Matteo Collina',
    tag: 'Node.js',
    title: 'Node.js Security & Performance',
    videoUrl: 'https://youtube.com/watch?v=node-security',
    year: 2023,
  },
  {
    conference: 'Deno Conf',
    description: 'Why Deno 2.0 is ready for production and how to migrate.',
    duration: 35,
    slides: 'https://slides.com/deno/v2-production',
    speaker: 'Ryan Dahl',
    tag: 'Deno',
    title: 'Deno 2.0: Production Ready',
    year: 2024,
  },
  {
    conference: 'Frontend Masters Live',
    description: 'Testing strategies for modern React applications.',
    duration: 60,
    slides: 'https://slides.com/kent/react-testing',
    speaker: 'Kent C. Dodds',
    tag: 'Testing',
    title: 'React Testing Library Deep Dive',
    year: 2023,
  },
  // Real conference talks start here
  {
    conference: 'React Universe Conf',
    description: 'Highlights and trends from the React Native ecosystem in 2024.',
    duration: 40,
    speaker: 'Nicola Corti, Riccardo Cipolleschi',
    tag: 'React Native',
    title: 'What a year for React Native!',
    videoUrl: 'https://youtu.be/TaHbROUHJKY?si=Erq4VqDvcdipoV_W',
    year: 2024,
  },
  {
    conference: 'ViteConf',
    description: 'How Vite is revolutionizing the frontend build ecosystem.',
    duration: 40,
    speaker: 'Evan You',
    tag: 'Build Tools',
    title: 'Vite: The Build Tool Revolution',
    videoUrl: 'https://youtube.com/watch?v=vite-revolution',
    year: 2024,
  },
  {
    conference: 'React Conf',
    description: 'Understanding React Suspense patterns and concurrent features.',
    duration: 50,
    slides: 'https://slides.com/react/suspense-patterns',
    speaker: 'Rachel Nabors',
    tag: 'React',
    title: 'React Suspense Patterns',
    videoUrl: 'https://youtube.com/watch?v=suspense-patterns',
    year: 2023,
  },
  {
    conference: 'Next.js Conf',
    description: 'Server Components and the App Router revolution.',
    duration: 45,
    speaker: 'Lee Robinson',
    tag: 'Next.js',
    title: 'Next.js App Router Deep Dive',
    videoUrl: 'https://youtube.com/watch?v=app-router-deep',
    year: 2024,
  },
  {
    conference: 'TypeScript Congress',
    description: 'Building type-safe APIs with modern TypeScript.',
    duration: 40,
    slides: 'https://slides.com/typescript/type-safe-apis',
    speaker: 'Matt Pocock',
    tag: 'TypeScript',
    title: 'Type-Safe API Development',
    year: 2023,
  },
  {
    conference: 'React Conf',
    description: 'Optimizing React applications for better performance.',
    duration: 55,
    speaker: 'Luna Ruan',
    tag: 'Performance',
    title: 'React Performance Optimization',
    videoUrl: 'https://youtube.com/watch?v=react-perf-opt',
    year: 2024,
  },
  {
    conference: 'Vue.js Amsterdam',
    description: 'Building scalable Vue.js applications with modern tooling.',
    duration: 45,
    slides: 'https://slides.com/vue/scalable-apps',
    speaker: 'Sarah Drasner',
    tag: 'Vue.js',
    title: 'Scalable Vue.js Applications',
    videoUrl: 'https://youtube.com/watch?v=scalable-vue',
    year: 2024,
  },
  {
    conference: 'Remix Conf',
    description: 'Progressive enhancement and web standards with Remix.',
    duration: 50,
    speaker: 'Kent C. Dodds',
    tag: 'Remix',
    title: 'Progressive Enhancement with Remix',
    videoUrl: 'https://youtube.com/watch?v=progressive-remix',
    year: 2023,
  },
  {
    conference: 'Astro Launch Week',
    description: 'Content-driven development with modern web standards.',
    duration: 40,
    slides: 'https://slides.com/astro/content-driven',
    speaker: 'Matthew Phillips',
    tag: 'Astro',
    title: 'Content-Driven Web Development',
    year: 2024,
  },
  {
    conference: 'CSS Day',
    description: 'Modern CSS architecture and component design patterns.',
    duration: 35,
    speaker: 'Miriam Suzanne',
    tag: 'CSS',
    title: 'Modern CSS Architecture',
    videoUrl: 'https://youtube.com/watch?v=modern-css-arch',
    year: 2023,
  },
  {
    conference: 'JSConf',
    description: 'Modern JavaScript patterns and best practices for 2024.',
    duration: 50,
    slides: 'https://slides.com/js/modern-patterns',
    speaker: 'Kyle Simpson',
    tag: 'JavaScript',
    title: 'Modern JavaScript Patterns',
    year: 2024,
  },
  {
    conference: 'TailwindCSS Connect',
    description: 'Component-first design systems with Tailwind CSS.',
    duration: 40,
    speaker: 'Steve Schoger',
    tag: 'TailwindCSS',
    title: 'Component-First Design Systems',
    videoUrl: 'https://youtube.com/watch?v=component-first',
    year: 2023,
  },
  {
    conference: 'Vite Conf',
    description: 'Next-generation frontend tooling and build optimization.',
    duration: 45,
    slides: 'https://slides.com/vite/next-gen-tooling',
    speaker: 'Anthony Fu',
    tag: 'Build Tools',
    title: 'Next-Generation Frontend Tooling',
    year: 2024,
  },
  {
    conference: 'React Conf',
    description: 'State management patterns in modern React applications.',
    duration: 40,
    speaker: 'Daishi Kato',
    tag: 'State Management',
    title: 'Modern React State Management',
    videoUrl: 'https://youtube.com/watch?v=react-state-mgmt',
    year: 2023,
  },
  {
    conference: 'Chrome Dev Summit',
    description: 'New web platform features and browser capabilities.',
    duration: 40,
    slides: 'https://slides.com/chrome/web-platform',
    speaker: 'Chrome Team',
    tag: 'Web Platform',
    title: 'Web Platform Updates 2024',
    year: 2024,
  },
  {
    conference: 'Edge Conf',
    description: 'Building applications for edge computing environments.',
    duration: 50,
    speaker: 'Vercel Edge Team',
    tag: 'Edge Computing',
    title: 'Edge Computing for Frontend',
    videoUrl: 'https://youtube.com/watch?v=edge-frontend',
    year: 2023,
  },
  {
    conference: 'GraphQL Galaxy',
    description: 'Advanced GraphQL federation and schema design patterns.',
    duration: 55,
    slides: 'https://slides.com/apollo/graphql-federation',
    speaker: 'Apollo Team',
    tag: 'GraphQL',
    title: 'GraphQL Federation at Scale',
    year: 2024,
  },
  {
    conference: 'TypeScript Congress',
    description: 'Template literal types and advanced type manipulation.',
    duration: 45,
    speaker: 'Anders Hejlsberg',
    tag: 'TypeScript',
    title: 'Advanced TypeScript Patterns',
    videoUrl: 'https://youtube.com/watch?v=advanced-ts',
    year: 2023,
  },
  {
    conference: 'Remix Conf',
    description: 'Full-stack web development with Remix and modern standards.',
    duration: 50,
    slides: 'https://slides.com/remix/full-stack',
    speaker: 'Ryan Florence',
    tag: 'Remix',
    title: 'Full-Stack Web with Remix',
    year: 2024,
  },
  {
    conference: 'Astro Launch Week',
    description: 'Building fast, content-focused websites with Astro.',
    duration: 40,
    speaker: 'Fred Schott',
    tag: 'Astro',
    title: 'Astro: The Web Framework for Content',
    videoUrl: 'https://youtube.com/watch?v=astro-content',
    year: 2024,
  },
  {
    conference: 'TailwindCSS Connect',
    description: 'Advanced Tailwind CSS techniques and custom design systems.',
    duration: 35,
    slides: 'https://slides.com/tailwind/advanced-techniques',
    speaker: 'Adam Wathan',
    tag: 'TailwindCSS',
    title: 'Advanced Tailwind Techniques',
    year: 2023,
  },
  {
    conference: 'Storybook Day',
    description: 'Component-driven development and testing strategies.',
    duration: 45,
    speaker: 'Storybook Team',
    tag: 'Storybook',
    title: 'Component-Driven Development',
    videoUrl: 'https://youtube.com/watch?v=component-driven',
    year: 2024,
  },
  {
    conference: 'Electron Conf',
    description: 'Building cross-platform desktop apps with web technologies.',
    duration: 50,
    slides: 'https://slides.com/electron/desktop-apps',
    speaker: 'Electron Team',
    tag: 'Electron',
    title: 'Modern Desktop Apps with Electron',
    year: 2023,
  },
  {
    conference: 'Tauri Conf',
    description: 'Lightweight desktop applications with Rust and web frontends.',
    duration: 40,
    speaker: 'Tauri Team',
    tag: 'Tauri',
    title: 'Tauri: Rust-Powered Desktop Apps',
    videoUrl: 'https://youtube.com/watch?v=tauri-desktop',
    year: 2024,
  },
  {
    conference: 'Web3 Frontend',
    description: 'Building user interfaces for decentralized applications.',
    duration: 55,
    slides: 'https://slides.com/web3/frontend-dapps',
    speaker: 'Ethereum Foundation',
    tag: 'Web3',
    title: 'Frontend for Decentralized Apps',
    year: 2023,
  },
  {
    conference: 'React India',
    description: 'Server components and the future of React architecture.',
    duration: 60,
    speaker: 'Sebastian Markbåge',
    tag: 'React',
    title: 'React Server Components Deep Dive',
    videoUrl: 'https://youtube.com/watch?v=rsc-deep-dive',
    year: 2024,
  },
  {
    conference: 'JSConf EU',
    description: 'Machine learning in the browser with TensorFlow.js.',
    duration: 45,
    slides: 'https://slides.com/tensorflow/browser-ml',
    speaker: 'TensorFlow Team',
    tag: 'Machine Learning',
    title: 'ML in the Browser with TensorFlow.js',
    year: 2023,
  },
  {
    conference: 'Web Performance Conf',
    description: 'Core Web Vitals optimization strategies for 2024.',
    duration: 40,
    speaker: 'Google Web Team',
    tag: 'Performance',
    title: 'Core Web Vitals Optimization',
    videoUrl: 'https://youtube.com/watch?v=cwv-optimization',
    year: 2024,
  },
  {
    conference: 'Node.js Interactive',
    description: 'Building real-time applications with Node.js and WebSockets.',
    duration: 50,
    slides: 'https://slides.com/nodejs/realtime-apps',
    speaker: 'Node.js Foundation',
    tag: 'Node.js',
    title: 'Real-time Apps with Node.js',
    year: 2023,
  },
  {
    conference: 'Bun Conf',
    description: 'Fast JavaScript runtime and package manager for modern development.',
    duration: 35,
    speaker: 'Jarred Sumner',
    tag: 'Bun',
    title: 'Bun: The Fast JavaScript Runtime',
    videoUrl: 'https://youtube.com/watch?v=bun-runtime',
    year: 2024,
  },
  {
    conference: 'Fresh Conf',
    description: 'Island architecture and edge-side rendering with Fresh.',
    duration: 40,
    slides: 'https://slides.com/deno/fresh-islands',
    speaker: 'Deno Team',
    tag: 'Fresh',
    title: 'Fresh: Island Architecture',
    year: 2024,
  },
  {
    conference: 'Qwik City',
    description: 'Resumability and instant-on web applications.',
    duration: 45,
    speaker: 'Miško Hevery',
    tag: 'Qwik',
    title: 'Qwik: Resumable Web Applications',
    videoUrl: 'https://youtube.com/watch?v=qwik-resumable',
    year: 2023,
  },
  {
    conference: 'SolidJS Conf',
    description: 'Fine-grained reactivity without virtual DOM overhead.',
    duration: 50,
    slides: 'https://slides.com/solid/fine-grained-reactivity',
    speaker: 'Ryan Carniato',
    tag: 'SolidJS',
    title: 'SolidJS: Fine-Grained Reactivity',
    year: 2024,
  },
  {
    conference: 'React Universe Conf',
    description: 'Highlights and trends from the React Native ecosystem in 2024.',
    duration: 40,
    speaker: 'Nicola Corti, Riccardo Cipolleschi',
    tag: 'React Native',
    title: 'What a year for React Native!',
    videoUrl: 'https://youtu.be/TaHbROUHJKY?si=Erq4VqDvcdipoV_W',
    year: 2024,
  },
  {
    conference: 'React Universe Conf',
    description: 'Major updates and a new debugging experience for React Native.',
    duration: 40,
    speaker: 'Alex Hunt',
    tag: 'React Native',
    title: 'The New React Native Debugger',
    videoUrl: 'https://youtu.be/OwivVpg6Luc?si=mHaUnxNjplfq28Ks',
    year: 2024,
  },
  {
    conference: 'React Universe Conf',
    description: 'How the network impacts React apps and strategies to manage complexity.',
    duration: 40,
    speaker: 'Kent C. Dodds',
    tag: 'React',
    title: 'Abracadabra: The vanishing network',
    videoUrl: 'https://youtu.be/E8LLty9rTWw?si=gsX4gz1pKWj4savq',
    year: 2024,
  },
  {
    conference: 'React Universe Conf',
    description: 'Building React Native apps for Apple Vision Pro and spatial computing.',
    duration: 40,
    speaker: 'Oskar Kwaśniewski',
    tag: 'React Native',
    title: 'React Native ❤️ Apple Vision Pro: Your App in the New Dimension',
    videoUrl: 'https://youtu.be/rGpVxi6oS68?si=8BhgFqy-d0jsO5Fy',
    year: 2024,
  },
  {
    conference: 'React Universe Conf',
    description:
      'Learn how modern React patterns, Actions, and View Transitions enable smooth, reliable async UI in Next.js App Router.',
    duration: 20,
    longDescription: 'Handling async operations in UI components can be tricky—flickering pending states, inefficient state updates, and unstable interfaces are common issues. Modern React patterns address these challenges through concurrent rendering and React 19 Actions, offering more predictable async workflows and reusable patterns.\n\nIn the context of the Next.js App Router, this session will demonstrate how React Server Components streamline data fetching while Actions handle async operations with built-in optimistic updates and pending states. Looking ahead, we\'ll explore how View Transitions will integrate with these patterns to enable fluid visual updates.\n\nKey takeaways:\n• Understanding concurrent rendering and its impact on async UIs\n• Leveraging React 19 Actions for predictable async workflows\n• Building reusable components with built-in pending states\n• Implementing optimistic updates effectively\n• Future-proofing with View Transitions\n• Best practices for Next.js App Router integration\n\nYou\'ll leave with practical strategies for building reusable components while ensuring a smooth, reliable user experience.',
    speaker: 'Aurora Scharff',
    tag: 'React',
    title: 'Modern React Patterns: Concurrent Rendering, Actions & Whats Next',
    year: 2025,
  },
  // React Universe Conf 2025 Agenda
  {
    conference: 'React Universe Conf',
    description: 'Opening keynote from React Native Core Team members.',
    duration: 30,
    speaker: 'Nicola Corti, Riccardo Cipolleschi',
    tag: 'React Native',
    title: 'Opening Keynote',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Updates on React Native releases and roadmap towards stability.',
    duration: 25,
    speaker: 'Jorge Cohen',
    tag: 'React Native',
    title: 'React Native Releases in 2025: Towards a stable future',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Presentation from Lynx architecture team.',
    duration: 25,
    speaker: 'Xuan Huang',
    tag: 'Architecture',
    title: 'To be announced',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Comprehensive introduction to AI SDK version 5.',
    duration: 25,
    speaker: 'Matt Pocock',
    tag: 'AI',
    title: 'AI SDK v5: A Crash Course',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Exploring the powerful combination of Hermes JavaScript engine and Node API.',
    duration: 25,
    speaker: 'Vladimir Morozov, Khalef Hosany',
    tag: 'JavaScript',
    title: 'Hermes + Node API: A match made in Heaven',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Upcoming announcement from Margelo CEO.',
    duration: 25,
    speaker: 'Marc Rousavy',
    tag: 'React Native',
    title: 'To be announced',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Deep dive into SQLite and its role in modern AI applications.',
    duration: 25,
    speaker: 'D. Richard Hipp',
    tag: 'Database',
    title: 'Structured Query Language: The Other AI',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Exploring the evolution and different generations of React.',
    duration: 15,
    longDescription: 'This talk explores the generational divide in React development, examining how different learning journeys have shaped developers\' approaches to the framework.\n\nWe\'ll trace React\'s evolution from the "Class Component Generation" to the "Hooks Generation," to the emerging "Compiler Generation" understanding how these distinct starting points influence coding styles, preferences, and best practices.\n\nKey topics covered:\n• The Class Component Generation: Developers who learned React through lifecycle methods\n• The Hooks Generation: Those who started with functional components and hooks\n• The Compiler Generation: New developers entering with React Compiler\n• How each generation approaches state management, side effects, and component architecture\n• Bridging the gaps between different React paradigms\n\nWhether you\'re a seasoned React developer or just starting your journey, this talk will help you understand the rich history of React development patterns and how they continue to evolve.',
    speaker: 'Anisha Malde',
    tag: 'React',
    title: 'The Generations of React',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Interactive panel discussion with industry experts.',
    duration: 45,
    speaker: 'Panel',
    tag: 'Discussion',
    title: 'Panel Discussion',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Building pluggable tracing frameworks using Nitro Modules.',
    duration: 25,
    speaker: 'Artur Morys-Magiera, Dominik Dolny',
    tag: 'Performance',
    title: 'Retraceable: pluggable tracing framework using Nitro Modules',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Creating scalable ecosystems that bridge C++ and JavaScript.',
    duration: 25,
    speaker: 'Dr Kubilay Ahmet Küçük',
    tag: 'Architecture',
    title: 'A Complete Toolset for a Scalable C++ & JavaScript Ecosystem',
    year: 2025,
  },
  {
    conference: 'React Universe Conf',
    description: 'Implementing effective A/B testing strategies in React Native applications.',
    duration: 25,
    speaker: 'Violina Popova',
    tag: 'Testing',
    title: 'Is Your App Guesswork? A/B Testing the Truth in React Native',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Strategies for monetizing React Native applications through in-app purchases.',
    duration: 20,
    speaker: 'Perttu Lähteenlahti',
    tag: 'React Native',
    title: 'Monetizing Your React Native App with In-App Purchases',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Evolution of keyboard management techniques in React Native applications.',
    duration: 24,
    speaker: 'Kiryl Ziusko',
    tag: 'React Native',
    title: 'Keyboard Management Evolution in React Native',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Modern authentication patterns and security in React Native apps.',
    duration: 18,
    speaker: 'Laura Beatris',
    tag: 'Security',
    title: 'The Future of Authentication in React Native',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Best practices for building secure React Native applications.',
    duration: 19,
    speaker: 'Jacob Arvidsson',
    tag: 'Security',
    title: 'Building Secure React Native Apps',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Implementing live streaming in React Native without deep WebRTC knowledge.',
    duration: 10,
    speaker: 'Miłosz Filimowski',
    tag: 'React Native',
    title: 'React Native Live Streaming with Zero WebRTC Knowledge',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Software composing techniques for Expo development targeting project managers.',
    duration: 20,
    speaker: 'Tomasz Sułkowski',
    tag: 'Expo',
    title: 'Software Composing: Expo Development for Your PM',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Using TanStack Query to improve developer and user experience in Expo apps.',
    duration: 19,
    speaker: 'Devlin Duldulao',
    tag: 'Expo',
    title: 'TanStack Query in Expo Apps: Improving DX and UX Like No Other',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Making React Native development accessible to everyone.',
    duration: 25,
    speaker: 'Enzo Manuel Mangano',
    tag: 'React Native',
    title: 'Everybody Can Cook with React Native',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'A brief history of streaming technologies and Le Chat implementation.',
    duration: 25,
    speaker: 'Delphine Bugner',
    tag: 'Streaming',
    title: 'Le Chat and a Brief History of Streaming',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Progress towards a stable JavaScript API in React Native.',
    duration: 25,
    speaker: 'Alex Hunt',
    tag: 'JavaScript',
    title: 'Towards a Stable JavaScript API',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Integrating native code and capabilities into Expo applications.',
    duration: 25,
    speaker: 'Keith Kurak',
    tag: 'Expo',
    title: 'Embracing Native Code and Capabilities in Your Expo App',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Scaling brownfield React Native development with micro-apps architecture.',
    duration: 25,
    speaker: 'Sojin Park',
    tag: 'React Native',
    title: 'Brownfield React Native at Scale: Ship Dozens of Micro-Apps Daily',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Large-scale React Native development strategies in the AI era.',
    duration: 25,
    speaker: 'Rafael Mendiola',
    tag: 'React Native',
    title: 'Large-Scale React Native Development in the Age of AI',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Creating premium user experiences and quality UX in React Native.',
    duration: 25,
    speaker: 'Saúl Sharma',
    tag: 'UX',
    title: 'Building React Native Apps with Premium Feel and Quality UX',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Implementing small language models on mobile devices.',
    duration: 25,
    speaker: 'Mateusz Kopciński',
    tag: 'AI',
    title: 'Running Small Language Models on Your Phone',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Understanding the bigger picture of React Native development.',
    duration: 25,
    speaker: 'Anisha Malde, Łukasz Chludziński',
    tag: 'React Native',
    title: 'The Bigger Picture',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Evolution of party invites through App Clips technology.',
    duration: 25,
    speaker: 'Alex Chou',
    tag: 'iOS',
    title: 'The Next Evolution of the Party Invite is an App Clip',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Enterprise CI/CD scaling and migration success stories.',
    duration: 25,
    speaker: 'Michael Blanchard',
    tag: 'DevOps',
    title: 'Scaling Enterprise CI/CD: A Migration Success Story',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'High-performance 3D animations in React Native using WebGPU.',
    duration: 25,
    speaker: 'Krzysztof Piaskowy',
    tag: 'Performance',
    title: 'WebGPU === High Performant 3D Animations in React Native',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Introduction to Radon IDE and its development benefits.',
    duration: 25,
    speaker: 'Krzysztof Magiera',
    tag: 'DevTools',
    title: 'Radon IDE – Code with Glee',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Creative approaches to React Native development and innovation.',
    duration: 25,
    speaker: 'Kim Chouard',
    tag: 'React Native',
    title: 'Mozart Never Had React Native: You Do',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Optimizing list performance for peak user experience.',
    duration: 25,
    speaker: 'Jay Meistrich',
    tag: 'Performance',
    title: 'Legend List: Optimizing for Peak List Performance',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'The future of React Native after legacy architecture.',
    duration: 25,
    speaker: 'Nico Corti, Riccardo Cipolleschi',
    tag: 'React Native',
    title: 'Life After Legacy: The New Architecture Future',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Deploying Expo applications to orbit and space platforms.',
    duration: 25,
    speaker: 'Aaron Grider',
    tag: 'Expo',
    title: 'Expo on Orbit',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Universal deployment strategies using Expo Router.',
    duration: 25,
    speaker: 'Evan Bacon',
    tag: 'Expo',
    title: 'Deploy Everywhere with Expo Router',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
  {
    conference: 'App.js Conf',
    description: 'Opening keynote presentation for App.js Conf 2025.',
    duration: 45,
    speaker: 'Charlie Cheever, Jon Samp',
    tag: 'Keynote',
    title: 'Keynote',
    videoUrl: 'https://youtube.com/playlist?list=PLjDdmg_b5_91App_js_Conf_2025',
    year: 2025,
  },
];

async function seed() {
  await prisma.talk.deleteMany({});
  console.info('[SEED] Deleted all existing talk records');

  await Promise.all(
    TALKS.map(talk => {
      return prisma.talk.create({
        data: {
          conference: talk.conference,
          description: talk.description,
          duration: talk.duration,
          longDescription: talk.longDescription,
          slides: talk.slides,
          speaker: talk.speaker,
          tag: talk.tag,
          title: talk.title,
          videoUrl: talk.videoUrl,
          year: talk.year,
        },
      });
    }),
  )
    .then(() => {
      return console.info('[SEED] Successfully created talk records');
    })
    .catch(e => {
      return console.error('[SEED] Failed to create talk records', e);
    });
}

seed();
